### ISSUE TITLE
LoadingIndicator does not show percentage

### ISSUE THREAD

**Issue by amrita-syn** [cornerstonejs/react-cornerstone-viewport#42]
The LoadingIndicator does not show percentage - as it never receives it. 

https://github.com/cornerstonejs/react-cornerstone-viewport/blob/7a669e715c47159821d419d3bb9d07bf1e43e742/src/CornerstoneViewport/CornerstoneViewport.js#L280

I am very happy to see the WADO loader now emitting the load progress events but it's not usable, at least in this viewport, because of the above. Can this be fixed?

**Comment by dannyrb** [comment]
That sounds like a reasonable enhancement. It's likely not at the top of our list, but I would be more than happy to review a community PR if it were on top of these incoming changes:

https://github.com/cornerstonejs/react-cornerstone-viewport/pull/41

(Or master, if at the time of reading the above PR is merged)

**Comment by amrita-syn** [comment]
> That sounds like a reasonable enhancement. It's likely not at the top of our list, but I would be more than happy to review a community PR if it were on top of these incoming changes:
> 
> #41
> 
> (Or master, if at the time of reading the above PR is merged)

I was afraid of getting this reply. :) I am a happy consumer of this awesome library. But, I end up reading a lot of code (and then filtering the relevant parts) to make any changes. @dannyrb , I wouldn't mind doing the coding if you can give some pointers on what needs to be done.

**Comment by dannyrb** [comment]
I'm a bit swamped, but I'll try to think on this and give you a good answer before EOD tomorrow. Don't hesitate to `@mention` me if I don't make my way back here.

**Comment by amrita-syn** [comment]
@dannyrb Any update please?

**Comment by dannyrb** [comment]
👋 Hi @amrita-syn, I _juuusst_ merged the PR previously mentioned.

### For stack loading:

- We track [`numImagesLoaded` in state](https://github.com/cornerstonejs/react-cornerstone-viewport/blob/master/src/CornerstoneViewport/CornerstoneViewport.js#L100)
- It is [reset when the imageIds (the stack) is updated](https://github.com/cornerstonejs/react-cornerstone-viewport/blob/master/src/CornerstoneViewport/CornerstoneViewport.js#L210)
- We use cornerstone's [`onImageLoaded` event to increment it's value](https://github.com/cornerstonejs/react-cornerstone-viewport/blob/master/src/CornerstoneViewport/CornerstoneViewport.js#L561-L567)

That's currently the best bit of data for a rough estimate of what has been loaded. It's worth noting that loading is a bit more complicated than this, because cornerstone will cache images outside of the lifecycle of the component. It's a "Least Recently Used" (LRU) cache, so old data will eventually be purged if you exceed the cache's size.

It also looks like we might be prefetching image's in our stack in _reverse_ order. It should probably start from 0 and increment to be more useful.

### For Image Loading:

This matters more for very slow connections, or very large images (mostly multiframe?). The [`cornerstone-wado-image-loader` raises a "cornerstoneimageloadprogress" event](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/31a9b5a5eb267cfdfcf6db45218ad70c6d7ee115/src/imageLoader/internal/xhrRequest.js#L80-L108) that could be used to collect and report on per-image load progress.

### Customizing Things

- [Custom Overlay example](https://react.cornerstonejs.org/custom-overlay)

We don't expose much data to this, but could provide more to allow for more information rich overlays. Any custom component could also leverage the same cornerstone events to capture event data the same way the `react-cornerstone-viewport` does.

Similar to the "Custom Overlay", I'm open to either modifying the base loading indicator, or adding a prop to provide a custom one.

**Comment by amrita-syn** [comment]
Finally got to this. :) 
@dannyrb
