### ISSUE TITLE
Creating player with isPlaying=true doesn't work

### ISSUE THREAD

**Issue by dbousamra** [cornerstonejs/react-cornerstone-viewport#52]
I am pretty sure it's related to this line: https://github.com/cornerstonejs/react-cornerstone-viewport/blob/master/src/CornerstoneViewport/CornerstoneViewport.js#L264

It checks against `prevProps.isPlaying`, which is always set to true on first mount. So `shouldStart` is false always.

Here is some example code highlighting this issue:

https://codesandbox.io/s/flamboyant-star-s3e3u

**Comment by dannyrb** [comment]
@dbousamra are you comfortable authoring a pull request to fix this issue?

**Comment by dbousamra** [comment]
Sure. Just wanted to check this was an actual issue and not something I was misunderstanding.

**Comment by dannyrb** [comment]
I think you've correctly identified the intent and the issue at hand. We `default` to false when we use this component in `OHIF`. After that, we make changes by toggling `isPlaying` or the frameRate; which is why we haven't observed this issue.

This is the logic for `playClip`: [src/stackTools/playClip.js](https://github.com/cornerstonejs/cornerstoneTools/blob/3cd6d0c567a4915606225564e148db347c63c436/src/stackTools/playClip.js#L100-L282)

> Starts playing a clip or adjusts the frame rate of an already playing clip.  framesPerSecond is optional and defaults to 30 if not specified.  A negative framesPerSecond will play the clip in reverse. The element must be a stack of images

I think there's two ways we could fix this:

In `componentDidMount`, if `isPlaying` is `true`, we could call `playClip`. This takes care of setting the initial state based on props.

OR

In `componentDidUpdate` we remove the `prevIsPlaying` checks.

I think I prefer the first approach. It looks like if we call `playClip` for other prop updates, it would stop, update the settings, start. I'm unsure of how this would impact the behavior.

**Comment by dbousamra** [comment]
Thanks, this was a great summary. I've attached a PR that should fix things.
